resources:
    App\Entity\TvShow:
        shortName: 'Tvshow'
        itemOperations:
            get:
                path: 'tvshows/{id}'
                controller: App\Controller\TvShowController