resources:
    App\Entity\TvShowEpisode:
        shortName: 'Episode'
        attributes:
            normalization_context:
                groups: read
            denormalization_context:
                groups: write