resources:
    App\Entity\TvShowSeason:
        shortName: 'Season'
        attributes:
            normalization_context:
                groups: read
            denormalization_context:
                groups: write