resources:
    App\Entity\TvShow:
        shortName: 'Tvshow'
        attributes:
            normalization_context:
                groups: read
            denormalization_context:
                groups: write
        collectionOperations:
            get: ~
            post:
                security: 'is_granted("ROLE_ADMIN")'