api_platform:
    eager_loading:
        max_joins: 50
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/config/api_platform/resources']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
